config/routes.rb
Rails.application.routes.draw do
  get '/vendors' => 'vendors#index'
  get '/vendors/new' => 'vendors#new'
  post 'vendors' => 'vendors#create'
  get 'vendors/:id' => 'vendors#show' ,as: :vendor
  get 'vendors/:id/edit' => 'vendors#edit', as: :edit_vendor
  patch 'vendors/:id' => 'vendors#update'
  delete 'vendors/:id' => 'vendors#destroy' ,as: :delete_vendor

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
    @vendors = Vendor.all
  end
  def new
    @vendor = Vendor.new
  end
  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      redirect_to '/vendors'
    else
      render 'new'
    end
  end

  def vendor_params
    params.require(:vendor).permit(:vendor_id,:name,:address,:contact_no)
  end
  def show
    @vendor = Vendor.find(params[:id])
  end
  def edit
    @vendor = Vendor.find(params[:id])
  end
  def update
    @vendor = Vendor.find(params[:id])
    if @vendor.update(vendor_params)
      redirect_to @vendor
    else
      render 'edit'
    end
end

  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy
      redirect_to '/vendors'
    end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head >
  <title>Cabzollo</title>
  <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application.js', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="communication.js"></script>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/vendors/edit.html.erb
<h1><CENTER>Update</CENTER></h1>

<%= form_for(@vendor) do |f| %>
    NAME
    <%= f.text_area :name %>
    ADDRESS
    <%= f.text_area :address %>
    CONTACT
    <%= f.text_area :contact_no %>
    <div class="btn">
      <%= f.submit "Update" %>
    </div>
<% end %>

app/views/vendors/index.html.erb
<div class="venodrs">
    <%= link_to 'New Vendor', "vendors/new" %><br>
  <table>
    <tr>
      <th>Vendor_id</th>
      <th>Name</th>
      <th>Address</th>
      <th>Contact</th>
      <th>Created at</th>
    </tr>
  <% @vendors.each do |vendor| %>
        <tr>
     <td> <%= vendor.vendor_id %></td>
     <td>  <%= vendor.name %></td>
      <td><%= vendor.address %></td>
      <td><%= vendor.contact_no %></td>
      <td><%= vendor.created_at %></td>
          <td><%= link_to 'See more', vendor_path(vendor) %></td>
        </tr>
<% end %>
    </table>
    </div>

app/views/vendors/new.html.erb
<div class="create">
  <div class="container">
 <h1><CENTER>Enroll new Vendor</CENTER></h1>

    <%= form_for(@vendor) do |f| %>

          ID
          <%= f.text_area :vendor_id %>
        NAME
          <%= f.text_area :name %>
        ADDRESS
          <%= f.text_area :address %>
        CONTACT
          <%= f.text_area :contact_no %>
        <div class="actions">
          <%= f.submit "Create" %>
        </div>
        <% end %>

  </div>
</div>

app/views/vendors/show.html.erb
<div>
  <table>
    <tr>
      <td>Vendor</td>
      <td> Name</td>
      <td>Address</td>
      <td> Contact_No</td>
    </tr>
  <tr>
    <td><%= @vendor.vendor_id %></td>
    <td><%= @vendor.name %></td>
    <td><%= @vendor.address %></td>
    <td><%= @vendor.contact_no %></td>
    <td><%= link_to 'Update', edit_vendor_path(@vendor) %></td>
    <td><%= link_to 'Destroy', delete_vendor_path(@vendor) ,method: :delete,
    data: { confirm: 'Are you sure?' } %></td>
    </tr>
    </table>
</div>